namespace Bistrotic.WorkItems.Infrastructure.DevOps
{
    /// <summary>
    /// Class QuerySettings.
    /// </summary>
    /// <autogeneratedoc/>
    internal class DevOpsSettings
    {
        /// <summary>
        /// Gets or sets the personal access token.
        /// </summary>
        /// <value>The personal access token.</value>
        /// <autogeneratedoc/>
        public string? PersonalAccessToken { get; set; }

        /// <summary>
        /// Gets or sets the server.
        /// </summary>
        /// <value>The server.</value>
        /// <autogeneratedoc/>
        public string? Server { get; set; }
    }
}