namespace Bistrotic.WorkItems.Infrastructure.DevOps
{
    /// <summary>
    /// Class WorkItemFieldType.
    /// </summary>
    /// <autogeneratedoc/>
    public static class WorkItemFieldType
    {
        /// <summary>
        /// The activity.
        /// </summary>
        /// <autogeneratedoc/>
        public const string Activity = "Microsoft.VSTS.Common.Activity";

        public const string AreaId = "System.AreaId";

        /// <summary>
        /// The area path The area of the product with which this bug is associated
        /// </summary>
        public const string AreaPath = "System.AreaPath";

        /// <summary>
        /// The assigned to The person currently working on this bug
        /// </summary>
        /// <autogeneratedoc/>
        public const string AssignedTo = "System.AssignedTo";

        public const string AttachedFileCount = "System.AttachedFileCount";

        public const string AuthorizedAs = "System.AuthorizedAs";

        public const string AuthorizedDate = "System.AuthorizedDate";

        public const string ChangedBy = "System.ChangedBy";

        public const string ChangedDate = "System.ChangedDate";

        /// <summary>
        /// The completed work.
        /// </summary>
        /// <autogeneratedoc/>
        public const string CompletedWork = "Microsoft.VSTS.Scheduling.CompletedWork";

        public const string CreatedBy = "System.CreatedBy";

        public const string CreatedDate = "System.CreatedDate";

        /// <summary>
        /// The external link count
        /// </summary>
        /// <autogeneratedoc/>
        public const string ExternalLinkCount = "System.ExternalLinkCount";

        public const string HyperLinkCount = "System.HyperLinkCount";

        public const string Id = "System.Id";

        /// <summary>
        /// The iteration identifier
        /// </summary>
        /// <autogeneratedoc/>
        public const string IterationId = "System.IterationId";

        /// <summary>
        /// The iteration path The iteration within which this bug will be fixed
        /// </summary>
        public const string IterationPath = "System.IterationPath";

        public const string NodeName = "System.NodeName";

        /// <summary>
        /// The original estimate.
        /// </summary>
        /// <autogeneratedoc/>
        public const string OriginalEstimate = "Microsoft.VSTS.Scheduling.OriginalEstimate";

        /// <summary>
        /// The reason "The reason why the bug is in the current state"
        /// </summary>
        public const string Reason = "System.Reason";

        /// <summary>
        /// The remaining work.
        /// </summary>
        /// <autogeneratedoc/>
        public const string RemainingWork = "Microsoft.VSTS.Scheduling.RemainingWork";

        public const string Rev = "System.Rev";
        public const string RevisedDate = "System.RevisedDate";

        /// <summary>
        /// The state New = for triage; Active = not yet fixed; Resolved = fixed not yet verified;
        /// Closed = fix verified.
        /// </summary>
        public const string State = "System.State";

        public const string TeamProject = "System.TeamProject";

        /// <summary>
        /// The title type.
        /// </summary>
        /// <autogeneratedoc/>
        public const string Title = "System.Title";

        public const string Watermark = "System.Watermark";
        public const string WorkItemType = "System.WorkItemType";

        /// <summary>
        /// The work item type.
        /// </summary>
        /// <autogeneratedoc/>
        public const string WorkItemType = "System.WorkItemType";
    }
}