namespace Bistrotic.Application.Queries
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Threading.Tasks;

    using Bistrotic.Application.Exceptions;
    using Bistrotic.Application.Messages;

    /// <summary>
    /// Implements the <see cref="IQueryDispatcher"/>.
    /// </summary>
    /// <seealso cref="IQueryDispatcher"/>
    /// <autogeneratedoc/>
    public class InMemoryQueryDispatcher : IQueryDispatcher
    {
        private readonly ImmutableDictionary<Type, Func<IQueryHandler>> _handlers;

        public InMemoryQueryDispatcher(Dictionary<Type, Func<IQueryHandler>> handlers)
        {
            _handlers = handlers?.ToImmutableDictionary() ?? throw new ArgumentNullException(nameof(handlers));
        }

        public Task<TResult> Dispatch<TQuery, TResult>(Envelope<TQuery> envelope)
            where TQuery : class, IQuery<TResult>
        {
            if (!_handlers.TryGetValue(envelope.Message.GetType(), out Func<IQueryHandler>? handlerFunc))
            {
                return Task.FromException<TResult>(new QueryHandlerNotFoundException(envelope.Message.GetType()));
            }
            IQueryHandler<TQuery, TResult>? handler = handlerFunc() as IQueryHandler<TQuery, TResult>;
            return handler?.Handle(envelope)
                ?? Task.FromException<TResult>(new InvalidQueryHandlerTypeException(handlerFunc().GetType(), typeof(IQueryHandler<TQuery, TResult>)));
        }

        public Task<object?> Dispatch(IEnvelope envelope)
        {
            if (!_handlers.TryGetValue(envelope.Message.GetType(), out Func<IQueryHandler>? handlerFunc))
            {
                return Task.FromException<object?>(new QueryHandlerNotFoundException(envelope.GetType()));
            }
            IQueryHandler? handler = handlerFunc();
            return handler?.Handle(envelope)
                ?? Task.FromException<object?>(new InvalidQueryHandlerTypeException(handlerFunc().GetType(), typeof(IQueryHandler)));
        }
    }
}