namespace Fiveforty.Commands
{
    /// <summary>
    /// Interface ICommandHandlerProvider
    /// </summary>
    /// <autogeneratedoc/>
    public interface ICommandHandlerProvider
    {
        /// <summary>
        /// Gets the handler.
        /// </summary>
        /// <param name="command">The command.</param>
        /// <returns>ICommandHandler.</returns>
        /// <autogeneratedoc/>
        ICommandHandler GetHandler(ICommand command);
    }
}