namespace Fiveforty.Commands
{
    using System.Threading.Tasks;

    /// <summary>
    /// Interface ICommandHandler
    /// </summary>
    /// <autogeneratedoc/>
    public interface ICommandHandler
    {
        /// <summary>
        /// Executes the specified command.
        /// </summary>
        /// <param name="command">The command.</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc/>
        Task Execute(ICommand command);
    }

    /// <summary>
    /// Interface ICommandHandler
    /// </summary>
    /// <typeparam name="TCommand">The type of the t command.</typeparam>
    /// <autogeneratedoc/>
    public interface ICommandHandler<TCommand> : ICommandHandler where TCommand : ICommand
    {
        /// <summary>
        /// Executes the specified command.
        /// </summary>
        /// <param name="command">The command.</param>
        /// <returns>Task.</returns>
        /// <autogeneratedoc/>
        Task Execute(TCommand command);
    }
}