// <auto-generated />
using System;
using Bistrotic.UblDocuments.Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bistrotic.UblDocuments.Migrations
{
    [DbContext(typeof(UblDocumentsDbContext))]
    [Migration("20210427162024_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bistrotic.UblDocuments.Application.Integration", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("IntegrationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId");

                    b.HasIndex("IntegrationDate");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ReceivedDate");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Aggregates.Invoice", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("AccountingCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingCostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CopyIndicator")
                        .HasColumnType("bit");

                    b.Property<string>("CustomizationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DueDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("IssueDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LineCountNumeric")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Partition")
                        .HasColumnType("int");

                    b.Property<string>("PaymentAlternativeCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaymentAlternativeExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaymentExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PricingCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricingExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProfileExecutionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("TaxPointDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UBLVersionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.Country", b =>
                {
                    b.Property<string>("IdentificationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Partition")
                        .HasColumnType("int");

                    b.HasKey("IdentificationCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.DocumentReference", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CopyIndicator")
                        .HasColumnType("bit");

                    b.Property<string>("DocumentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceKey")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceKey1")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceKey2")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceKey3")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceKey4")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("IssueDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LanguageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocaleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("InvoiceKey");

                    b.HasIndex("InvoiceKey1");

                    b.HasIndex("InvoiceKey2");

                    b.HasIndex("InvoiceKey3");

                    b.HasIndex("InvoiceKey4");

                    b.ToTable("DocumentReferences");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.InvoiceLine", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountingCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingCostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreeOfChargeIndicator")
                        .HasColumnType("bit");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceKey")
                        .HasColumnType("int");

                    b.Property<decimal>("InvoicedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineExtensionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentPurposeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("TaxPointDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("InvoiceKey");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Aggregates.Invoice", b =>
                {
                    b.HasOne("Bistrotic.UblDocuments.Types.Entities.DocumentReference", "DespatchDocumentReference")
                        .WithMany()
                        .HasForeignKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bistrotic.UblDocuments.Types.Entities.DeliveryTerms", "DeliveryTerms", b1 =>
                        {
                            b1.Property<int>("InvoiceKey")
                                .HasColumnType("int");

                            b1.Property<string>("AllowanceCharge")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("DeliveryLocation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ID")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LossRiskResponsibilityCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InvoiceKey");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceKey");
                        });

                    b.OwnsOne("Bistrotic.UblDocuments.Types.Entities.LegalMonetaryTotal", "LegalMonetaryTotal", b1 =>
                        {
                            b1.Property<int>("InvoiceKey")
                                .HasColumnType("int");

                            b1.Property<decimal>("AllowanceTotalAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("ChargeTotalAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("LineExtensionAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("PayableAlternativeAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("PayableAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("PayableRoundingAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("PrepaidAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("TaxExclusiveAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("TaxInclusiveAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("InvoiceKey");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceKey");
                        });

                    b.OwnsOne("Bistrotic.UblDocuments.Types.Entities.OrderReference", "OrderReference", b1 =>
                        {
                            b1.Property<int>("InvoiceKey")
                                .HasColumnType("int");

                            b1.Property<bool>("CopyIndicator")
                                .HasColumnType("bit");

                            b1.Property<string>("CustomerReference")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ID")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset?>("IssueDateTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int?>("Key")
                                .HasColumnType("int");

                            b1.Property<string>("OrderTypeCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SalesOrderID")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UUID")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InvoiceKey");

                            b1.HasIndex("Key");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceKey");

                            b1.HasOne("Bistrotic.UblDocuments.Types.Entities.DocumentReference", "DocumentReference")
                                .WithMany()
                                .HasForeignKey("Key");

                            b1.Navigation("DocumentReference");
                        });

                    b.OwnsOne("Bistrotic.UblDocuments.Types.Entities.Period", "InvoicePeriod", b1 =>
                        {
                            b1.Property<int>("InvoiceKey")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DescriptionCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal?>("DurationMeasure")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateTimeOffset?>("EndDateTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<DateTimeOffset?>("StartDateTime")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("InvoiceKey");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceKey");
                        });

                    b.Navigation("DeliveryTerms")
                        .IsRequired();

                    b.Navigation("DespatchDocumentReference");

                    b.Navigation("InvoicePeriod")
                        .IsRequired();

                    b.Navigation("LegalMonetaryTotal")
                        .IsRequired();

                    b.Navigation("OrderReference")
                        .IsRequired();
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.DocumentReference", b =>
                {
                    b.HasOne("Bistrotic.UblDocuments.Types.Aggregates.Invoice", null)
                        .WithMany("AdditionalDocumentReference")
                        .HasForeignKey("InvoiceKey");

                    b.HasOne("Bistrotic.UblDocuments.Types.Aggregates.Invoice", null)
                        .WithMany("ContractDocumentReference")
                        .HasForeignKey("InvoiceKey1");

                    b.HasOne("Bistrotic.UblDocuments.Types.Aggregates.Invoice", null)
                        .WithMany("OriginatorDocumentReference")
                        .HasForeignKey("InvoiceKey2");

                    b.HasOne("Bistrotic.UblDocuments.Types.Aggregates.Invoice", null)
                        .WithMany("ReceiptDocumentReference")
                        .HasForeignKey("InvoiceKey3");

                    b.HasOne("Bistrotic.UblDocuments.Types.Aggregates.Invoice", null)
                        .WithMany("StatementDocumentReference")
                        .HasForeignKey("InvoiceKey4");

                    b.OwnsOne("Bistrotic.UblDocuments.Types.Entities.Attachment", "Attachment", b1 =>
                        {
                            b1.Property<int>("DocumentReferenceKey")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("EmbeddedDocumentBinaryObject")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DocumentReferenceKey");

                            b1.ToTable("DocumentReferences");

                            b1.WithOwner()
                                .HasForeignKey("DocumentReferenceKey");

                            b1.OwnsOne("Bistrotic.UblDocuments.Types.Entities.ExternalReference", "ExternalReference", b2 =>
                                {
                                    b2.Property<int>("AttachmentDocumentReferenceKey")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("CharacterSetCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("DocumentHash")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("EncodingCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTimeOffset>("ExpiryDate")
                                        .HasColumnType("datetimeoffset");

                                    b2.Property<DateTime>("ExpiryTime")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FormatCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("HashAlgorithmMethod")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("MimeCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("URI")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("AttachmentDocumentReferenceKey");

                                    b2.ToTable("DocumentReferences");

                                    b2.WithOwner()
                                        .HasForeignKey("AttachmentDocumentReferenceKey");
                                });

                            b1.Navigation("ExternalReference")
                                .IsRequired();
                        });

                    b.OwnsOne("Bistrotic.UblDocuments.Types.Entities.Period", "ValidityPeriod", b1 =>
                        {
                            b1.Property<int>("DocumentReferenceKey")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DescriptionCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal?>("DurationMeasure")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateTimeOffset?>("EndDateTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<DateTimeOffset?>("StartDateTime")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("DocumentReferenceKey");

                            b1.ToTable("DocumentReferences");

                            b1.WithOwner()
                                .HasForeignKey("DocumentReferenceKey");
                        });

                    b.Navigation("Attachment")
                        .IsRequired();

                    b.Navigation("ValidityPeriod");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.InvoiceLine", b =>
                {
                    b.HasOne("Bistrotic.UblDocuments.Types.Aggregates.Invoice", null)
                        .WithMany("InvoiceLine")
                        .HasForeignKey("InvoiceKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Bistrotic.UblDocuments.Types.Entities.Period", "InvoicePeriod", b1 =>
                        {
                            b1.Property<int>("InvoiceLineKey")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DescriptionCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal?>("DurationMeasure")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateTimeOffset?>("EndDateTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<DateTimeOffset?>("StartDateTime")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("InvoiceLineKey");

                            b1.ToTable("InvoiceLines");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceLineKey");
                        });

                    b.OwnsOne("System.Collections.Generic.List<Bistrotic.UblDocuments.Types.Entities.OrderLineReference>", "OrderLineReference", b1 =>
                        {
                            b1.Property<int>("InvoiceLineKey")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Capacity")
                                .HasColumnType("int");

                            b1.HasKey("InvoiceLineKey");

                            b1.ToTable("InvoiceLines");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceLineKey");
                        });

                    b.Navigation("InvoicePeriod")
                        .IsRequired();

                    b.Navigation("OrderLineReference")
                        .IsRequired();
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Aggregates.Invoice", b =>
                {
                    b.Navigation("AdditionalDocumentReference");

                    b.Navigation("ContractDocumentReference");

                    b.Navigation("InvoiceLine");

                    b.Navigation("OriginatorDocumentReference");

                    b.Navigation("ReceiptDocumentReference");

                    b.Navigation("StatementDocumentReference");
                });
#pragma warning restore 612, 618
        }
    }
}
