// <auto-generated />
using Bistrotic.UblDocuments.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bistrotic.UblDocuments.Migrations
{
    [DbContext(typeof(UblDocumentsDbContext))]
    [Migration("20210419123728_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Aggregates.Invoice", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountingCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingCostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CopyIndicator")
                        .HasColumnType("bit");

                    b.Property<string>("CustomizationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<int>("LineCountNumeric")
                        .HasColumnType("int");

                    b.Property<int>("Partition")
                        .HasColumnType("int");

                    b.Property<string>("PaymentAlternativeCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaymentAlternativeExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaymentExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PricingCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricingExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProfileExecutionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UBLExtensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UBLVersionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.Country", b =>
                {
                    b.Property<string>("IdentificationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Partition")
                        .HasColumnType("int");

                    b.HasKey("IdentificationCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Bistrotic.UblInvoices.Application.UblIntegration", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageId");

                    b.ToTable("Integrations");
                });
#pragma warning restore 612, 618
        }
    }
}
