// <auto-generated />
using System;
using Bistrotic.UblDocuments.Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bistrotic.UblDocuments.Migrations
{
    [DbContext(typeof(UblDocumentsDbContext))]
    partial class UblDocumentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bistrotic.UblDocuments.Application.Integration", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("IntegrationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId");

                    b.HasIndex("IntegrationDate");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ReceivedDate");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Aggregates.Invoice", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountingCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingCostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CopyIndicator")
                        .HasColumnType("bit");

                    b.Property<string>("CustomizationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DueDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("IssueDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LineCountNumeric")
                        .HasColumnType("int");

                    b.Property<int>("Partition")
                        .HasColumnType("int");

                    b.Property<string>("PaymentAlternativeCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaymentAlternativeExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaymentExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PricingCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricingExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProfileExecutionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("TaxPointDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UBLVersionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.Country", b =>
                {
                    b.Property<string>("IdentificationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Partition")
                        .HasColumnType("int");

                    b.HasKey("IdentificationCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.InvoiceLine", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountingCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingCostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreeOfChargeIndicator")
                        .HasColumnType("bit");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceKey")
                        .HasColumnType("int");

                    b.Property<decimal>("InvoicedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineExtensionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentPurposeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UUID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("InvoiceKey");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Entities.InvoiceLine", b =>
                {
                    b.HasOne("Bistrotic.UblDocuments.Types.Aggregates.Invoice", null)
                        .WithMany("InvoiceLine")
                        .HasForeignKey("InvoiceKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bistrotic.UblDocuments.Types.Aggregates.Invoice", b =>
                {
                    b.Navigation("InvoiceLine");
                });
#pragma warning restore 612, 618
        }
    }
}
