namespace Bistrotic.Application.Commands
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Threading.Tasks;

    using Bistrotic.Application.Exceptions;
    using Bistrotic.Application.Messages;

    /// <summary>
    /// Implements the <see cref="ICommandDispatcher"/>.
    /// </summary>
    /// <seealso cref="ICommandDispatcher"/>
    /// <autogeneratedoc/>
    public class InMemoryCommandDispatcher : ICommandDispatcher
    {
        private readonly ImmutableDictionary<Type, Func<ICommandHandler>> _handlers;

        public InMemoryCommandDispatcher(Dictionary<Type, Func<ICommandHandler>> handlers)
        {
            _handlers = handlers?.ToImmutableDictionary() ?? throw new ArgumentNullException(nameof(handlers));
        }

        public Task Dispatch<TCommand>(Envelope<TCommand> envelope)
            where TCommand : ICommand
        {
            if (!_handlers.TryGetValue(envelope.Message.GetType(), out Func<ICommandHandler>? handlerFunc))
            {
                return Task.FromException(new CommandHandlerNotFoundException(envelope.Message.GetType()));
            }
            ICommandHandler<TCommand>? handler = handlerFunc() as ICommandHandler<TCommand>;
            return handler?.Handle(envelope)
                ?? Task.FromException(new InvalidCommandHandlerTypeException(handlerFunc().GetType(), typeof(ICommandHandler<TCommand>)));
        }

        public Task Dispatch(IEnvelope envelope)
        {
            if (!_handlers.TryGetValue(envelope.Message.GetType(), out Func<ICommandHandler>? handlerFunc))
            {
                return Task.FromException<object?>(new CommandHandlerNotFoundException(envelope.Message.GetType()));
            }
            ICommandHandler? handler = handlerFunc();
            return handler?.Handle(envelope)
                ?? Task.FromException<object?>(new InvalidCommandHandlerTypeException(handlerFunc().GetType(), typeof(ICommandHandler)));
        }
    }
}