namespace Bistrotic.Application.Queries
{
    using System;
    using System.Threading.Tasks;

    using Bistrotic.Application.Commands;
    using Bistrotic.Application.Messages;

    using MediatR;

    /// <summary>
    /// Implements the <see cref="IQueryDispatcher"/>.
    /// </summary>
    /// <seealso cref="IQueryDispatcher"/>
    /// <autogeneratedoc/>
    public class MediatRCommandDispatcher : ICommandDispatcher
    {
        private readonly IMediator _mediator;

        public MediatRCommandDispatcher(IMediator mediator)
        {
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
        }

        public Task Dispatch<TCommand>(Envelope<TCommand> envelope)
            where TCommand : class => _mediator.Send(new MediatREnvelope<TCommand>(envelope));

        Task ICommandDispatcher.Dispatch(IEnvelope envelope)
        {
            return _mediator.Send(envelope);
        }
    }
}